-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 21:02:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema miniPhp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miniPhp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miniPhp` DEFAULT CHARACTER SET utf8 ;
USE `miniPhp` ;

-- -----------------------------------------------------
-- Table `miniPhp`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniPhp`.`tb_usuario` (
  `cod_us` INT NOT NULL AUTO_INCREMENT,
  `nome_us` VARCHAR(45) NULL,
  `login_us` VARCHAR(45) NULL,
  `senha_us` VARCHAR(45) NULL unique,
  PRIMARY KEY (`cod_us`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniPhp`.`tb_editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniPhp`.`tb_editora` (
  `cod_ed` INT NOT NULL AUTO_INCREMENT,
  `nome_ed` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_ed`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniPhp`.`tb_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniPhp`.`tb_livro` (
  `cod_liv` INT NOT NULL AUTO_INCREMENT,
  `cod_ed` INT NULL,
  `titulo_liv` VARCHAR(45) NULL,
  `desc_liv` TEXT NULL,
  `img_liv` VARCHAR(45) NULL,
  `valor_liv` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_liv`),
  CONSTRAINT `fk_ed`
    FOREIGN KEY (`cod_ed`)
    REFERENCES `miniPhp`.`tb_editora` (`cod_ed`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniPhp`.`tb_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniPhp`.`tb_autor` (
  `cod_aut` INT NOT NULL AUTO_INCREMENT,
  `nome_aut` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_aut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniPhp`.`tb_autor_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniPhp`.`tb_autor_livro` (
  `cod_liv` INT NULL,
  `cod_autor` INT NULL,
    CONSTRAINT `FK_AUTOR`
    FOREIGN KEY (`cod_autor`)
    REFERENCES `miniPhp`.`tb_autor` (`cod_aut`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LIVRO`
    FOREIGN KEY (`cod_liv`)
    REFERENCES `miniPhp`.`tb_livro` (`cod_liv`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniPhp`.`tb_cad_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniPhp`.`tb_cad_livro` (
  `cod_us` INT NULL,
  `cod_liv` INT NULL,
   CONSTRAINT `fk_us`
    FOREIGN KEY (`cod_us`)
    REFERENCES `miniPhp`.`tb_usuario` (`cod_us`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_liv_us`
    FOREIGN KEY (`cod_liv`)
    REFERENCES `miniPhp`.`tb_livro` (`cod_liv`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



### INSERIR USUÁRIO

INSERT INTO TB_USUARIO(NOME_US, LOGIN_US, SENHA_US) VALUES ("josé","jose@gmail.com" ,md5("123"));

SELECT * FROM TB_USUARIO;
	 
## INSERIR EDITORA

INSERT INTO TB_EDITORA(NOME_ED) 
 VALUES("novatec"),
        ("alta books"),
        ("deitel");
 
 SELECT * FROM TB_EDITORA;

